log.py: use sdtout as last resort and update README
SysLogHandler connecting to a missing syslog socket.

Fixes the following exception:
FileNotFoundError: [Errno 2] No such file or directory

Signed-off-by: Flavio Fernandes <flavio@flaviof.com>